'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ApprovePayout
    
    '''<summary>
    '''LinkButtonBACK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonBACK As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtOTP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOTP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnUnlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnUnlock As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DropDownListUnlockPeriode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListUnlockPeriode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelNote As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TextBoxNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonAddNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddNote As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridViewOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewOrder As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PanelTrust2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelTrust2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LabelTrustLevelAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTrustLevelAction As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ButtonRunAutoSettle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonRunAutoSettle As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LabelCompletedOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCompletedOrders As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelKycDeclined control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelKycDeclined As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelOrderSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrderSpan As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelOrderSumEUR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrderSumEUR As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelOrderSumTotalEUR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrderSumTotalEUR As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabeltOrderSum30Days control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabeltOrderSum30Days As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCountryTrustLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCountryTrustLevel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCC_IsUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCC_IsUS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCardApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCardApproved As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCardRejected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCardRejected As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelNumberOfCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNumberOfCC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LinkButtonCreditCardUsedElsewhere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonCreditCardUsedElsewhere As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonEmailUsedElsewhere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonEmailUsedElsewhere As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonIpUsedElsewhere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonIpUsedElsewhere As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LabelPhoneCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPhoneCC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelPhoneIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPhoneIP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelPhoneCulture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPhoneCulture As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelDistinctNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDistinctNames As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelDistinctEmails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelDistinctEmails As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelKeyIndicators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelKeyIndicators As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ButtonPanelClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonPanelClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridViewKeyIndicator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewKeyIndicator As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''GridViewUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewUser As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DetailsViewNoteEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetailsViewNoteEdit As Global.System.Web.UI.WebControls.DetailsView
    
    '''<summary>
    '''GridViewSubOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewSubOrders As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDataSourceOrderChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceOrderChild As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''GridViewTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewTransaction As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''GridViewKyc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewKyc As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''GridViewAuditTrail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewAuditTrail As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDataSourceOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceOrder As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceOrderChildNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceOrderChildNote As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceTransaction As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceAuditTrail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAuditTrail As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceUserzz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceUserzz As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceUser As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''SqlDataSourceKycFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceKycFile As Global.System.Web.UI.WebControls.SqlDataSource
End Class
