'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MobilePage
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''PanelLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelLogin As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TextBoxCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonLogin As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LabelWrongPasswordText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelWrongPasswordText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PanelContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LabelRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelRole As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelMe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMe As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LinkButtonLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonLogout As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''PanelNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelNote As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TextBoxNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNote As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonAddNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddNote As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridViewOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewOrder As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''SqlDataSourceOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceOrder As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''PanelTrustCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelTrustCalculation As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LabelTrustMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTrustMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ButtonRunAutoSettle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonRunAutoSettle As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LabelCardApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCardApproved As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelTxLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTxLimit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCardTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCardTotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelPhoneVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPhoneVirtual As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelPhoneCardMatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPhoneCardMatch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelPhoneIpMatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPhoneIpMatch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LinkButtonCreditCardUsedElsewhere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonCreditCardUsedElsewhere As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButtonEmailUsedElsewhere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonEmailUsedElsewhere As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LabelCardUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCardUS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCompleted As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelOrderSpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrderSpan As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelOrderSUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrderSUM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelOrderTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrderTotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelOrder30Days control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelOrder30Days As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ButtonTrustUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonTrustUser As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonApproveCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonApproveCard As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LabelUserIsTrusted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelUserIsTrusted As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCards As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNames As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelEmails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelEmails As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelKycApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelKycApproved As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelKycDeclined control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelKycDeclined As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelPhoneCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPhoneCountry As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelCardCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCardCountry As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LabelIPCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelIPCountry As Global.System.Web.UI.WebControls.Label
End Class
