//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMC.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WMCResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WMCResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMC.Web.App_GlobalResources.WMCResources", typeof(WMCResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPT.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountholder Name.
        /// </summary>
        internal static string AccountholderName {
            get {
                return ResourceManager.GetString("AccountholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount cannot be empty..
        /// </summary>
        internal static string AmountCannotBeEmpty {
            get {
                return ResourceManager.GetString("AmountCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should be between.
        /// </summary>
        internal static string AmountShouldBeBetween {
            get {
                return ResourceManager.GetString("AmountShouldBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITCOIN ADDRESS.
        /// </summary>
        internal static string BitcoinAddress {
            get {
                return ResourceManager.GetString("BitcoinAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin address cannot be empty..
        /// </summary>
        internal static string BitcoinAddressCannotBeEmpty {
            get {
                return ResourceManager.GetString("BitcoinAddressCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{SiteName}/resources/tutorials/breadwallet-tutorial/.
        /// </summary>
        internal static string BitcoinAddressHelpContentBreadwalletSiteUrl {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentBreadwalletSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{SiteName}/resources/tutorials/Electrum-tutorial/.
        /// </summary>
        internal static string BitcoinAddressHelpContentElectrumSiteUrl {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentElectrumSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{SiteName}/resources/tutorials/jaxx-tutorial/.
        /// </summary>
        internal static string BitcoinAddressHelpContentJaxxSiteUrl {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentJaxxSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{SiteName}/tutorials/mycelium-tutorial/.
        /// </summary>
        internal static string BitcoinAddressHelpContentMycelium {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentMycelium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bitcoin address is automatically generated by your bitcoin wallet. If you already have a bitcoin wallet, please go to the recieve section of your wallet and locate, copy and paste the address into this field..
        /// </summary>
        internal static string BitcoinAddressHelpContentString1 {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you see an example of a bitcoin address: 13fyJo4nCkMBs7fd984kw9DBZjVVwwCn4v.
        /// </summary>
        internal static string BitcoinAddressHelpContentString2 {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not have a bitcoin wallet, please see our tutorials, that will guide you through the process of setting up a wallet, suitable for your needs..
        /// </summary>
        internal static string BitcoinAddressHelpContentString3 {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have here listed the different wallets that we recommend for the different devices:.
        /// </summary>
        internal static string BitcoinAddressHelpContentString4 {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone and iOS.
        /// </summary>
        internal static string BitcoinAddressHelpContentString5 {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentString5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android devices.
        /// </summary>
        internal static string BitcoinAddressHelpContentString6 {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentString6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop and desktop computers.
        /// </summary>
        internal static string BitcoinAddressHelpContentString7 {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentString7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced wallet.
        /// </summary>
        internal static string BitcoinAddressHelpContentString8 {
            get {
                return ResourceManager.GetString("BitcoinAddressHelpContentString8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin address is invalid..
        /// </summary>
        internal static string BitcoinAddressInvalid {
            get {
                return ResourceManager.GetString("BitcoinAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUY.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder name.
        /// </summary>
        internal static string CardholderName {
            get {
                return ResourceManager.GetString("CardholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not receiving the code? Please contact customer support..
        /// </summary>
        internal static string CodeNotReceiving {
            get {
                return ResourceManager.GetString("CodeNotReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        internal static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm that I have read and agree with the.
        /// </summary>
        internal static string ConfirmTermsAndConditions {
            get {
                return ResourceManager.GetString("ConfirmTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number.
        /// </summary>
        internal static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic instant transfer.
        /// </summary>
        internal static string DomesticInstantTransfer {
            get {
                return ResourceManager.GetString("DomesticInstantTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop File.
        /// </summary>
        internal static string DragAndDropFile {
            get {
                return ResourceManager.GetString("DragAndDropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT ORDER.
        /// </summary>
        internal static string EditOrder {
            get {
                return ResourceManager.GetString("EditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-MAIL.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address cannot be empty..
        /// </summary>
        internal static string EmailEmptyMessage {
            get {
                return ResourceManager.GetString("EmailEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid..
        /// </summary>
        internal static string EmailInvalidMessage {
            get {
                return ResourceManager.GetString("EmailInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to john@doe.com.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is too long. Please enter and email within 50 characters..
        /// </summary>
        internal static string EmailTooLongMessage {
            get {
                return ResourceManager.GetString("EmailTooLongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exact rate is set by the time of order completion, which we guarantee to be within 12 hours..
        /// </summary>
        internal static string ExactRateMessage {
            get {
                return ResourceManager.GetString("ExactRateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter firstname and surname..
        /// </summary>
        internal static string FirstNameSurNameEmptyMessage {
            get {
                return ResourceManager.GetString("FirstNameSurNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is too long. Please enter and email within 20 characters..
        /// </summary>
        internal static string FirstNameSurNameTooLongMessage {
            get {
                return ResourceManager.GetString("FirstNameSurNameTooLongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL NAME.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName cannot be empty..
        /// </summary>
        internal static string FullNameEmptyMessage {
            get {
                return ResourceManager.GetString("FullNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO BACK.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure this is your bitcoins address?.
        /// </summary>
        internal static string IsThisYourBitcoinAddressString {
            get {
                return ResourceManager.GetString("IsThisYourBitcoinAddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto:support@{SiteName}/.
        /// </summary>
        internal static string MailToAddress {
            get {
                return ResourceManager.GetString("MailToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to receiver.
        /// </summary>
        internal static string MessageToReceiver {
            get {
                return ResourceManager.GetString("MessageToReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOBILE.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number cannot be empty..
        /// </summary>
        internal static string MobileEmptyMessage {
            get {
                return ResourceManager.GetString("MobileEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOBILE Number.
        /// </summary>
        internal static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the purchase process we will verify your mobile number in order to prevent fraud. Please read our terms and conditions and privacy policy for more information..
        /// </summary>
        internal static string MobileNumberHelpContent {
            get {
                return ResourceManager.GetString("MobileNumberHelpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO, GO BACK.
        /// </summary>
        internal static string NoGoBack {
            get {
                return ResourceManager.GetString("NoGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order info.
        /// </summary>
        internal static string OrderInfo {
            get {
                return ResourceManager.GetString("OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        internal static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER SIZE.
        /// </summary>
        internal static string OrderSize {
            get {
                return ResourceManager.GetString("OrderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT INFORMATION.
        /// </summary>
        internal static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT INSTRUCTIONS.
        /// </summary>
        internal static string PaymentInstructions {
            get {
                return ResourceManager.GetString("PaymentInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order, {UserName}!.
        /// </summary>
        internal static string PaymentInstructionsPageContentString1 {
            get {
                return ResourceManager.GetString("PaymentInstructionsPageContentString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make a transfer to our account with the information stated below:.
        /// </summary>
        internal static string PaymentInstructionsPageContentString2 {
            get {
                return ResourceManager.GetString("PaymentInstructionsPageContentString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We guarantee to send you your bitcoins, no later the 12 hours after we have received your transfer..
        /// </summary>
        internal static string PaymentInstructionsPageContentString3 {
            get {
                return ResourceManager.GetString("PaymentInstructionsPageContentString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If any of the details stated here is not correct, please just submit a new order at by clicking the &quot;back button&quot; shown here. If the information above or in the box below is correct, then we kindly ask you to make a domestic bank transfer, to our account as stated above..
        /// </summary>
        internal static string PaymentInstructionsPageContentString4 {
            get {
                return ResourceManager.GetString("PaymentInstructionsPageContentString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The market rate at order completion.
        /// </summary>
        internal static string PaymentInstructionsPageContentString5 {
            get {
                return ResourceManager.GetString("PaymentInstructionsPageContentString5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For further information, please see our terms and condition.
        /// </summary>
        internal static string PaymentInstructionsPageContentString6 {
            get {
                return ResourceManager.GetString("PaymentInstructionsPageContentString6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you have any questions, please just reply to this mail or hit us op on our live chat. We always love to help!.
        /// </summary>
        internal static string PaymentInstructionsPageContentString7 {
            get {
                return ResourceManager.GetString("PaymentInstructionsPageContentString7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT SUCCEEDED.
        /// </summary>
        internal static string PaymentSucceeded {
            get {
                return ResourceManager.GetString("PaymentSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is verified successfully..
        /// </summary>
        internal static string PhoneNumberVerifiedSuccessfully {
            get {
                return ResourceManager.GetString("PhoneNumberVerifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government issued photo-ID.
        /// </summary>
        internal static string PhotoIDString1 {
            get {
                return ResourceManager.GetString("PhotoIDString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Passport or drivers license).
        /// </summary>
        internal static string PhotoIDString2 {
            get {
                return ResourceManager.GetString("PhotoIDString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACE ORDER.
        /// </summary>
        internal static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the six digit code we have sent you..
        /// </summary>
        internal static string PleaseInputSixDigitCode {
            get {
                return ResourceManager.GetString("PleaseInputSixDigitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof-of-Residency.
        /// </summary>
        internal static string ProofOfResidencyString1 {
            get {
                return ResourceManager.GetString("ProofOfResidencyString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Utility bill less than 3 months old).
        /// </summary>
        internal static string ProofOfResidencyString2 {
            get {
                return ResourceManager.GetString("ProofOfResidencyString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATE US ON TRUSTPILOT.
        /// </summary>
        internal static string RateUs {
            get {
                return ResourceManager.GetString("RateUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        internal static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you have any questions please.
        /// </summary>
        internal static string ReceiptPageFooterString1 {
            get {
                return ResourceManager.GetString("ReceiptPageFooterString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will revert to you! Stay tuned..
        /// </summary>
        internal static string ReceiptPageFooterString2 {
            get {
                return ResourceManager.GetString("ReceiptPageFooterString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards,.
        /// </summary>
        internal static string ReceiptPageFooterString3 {
            get {
                return ResourceManager.GetString("ReceiptPageFooterString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {SiteName}-team.
        /// </summary>
        internal static string ReceiptPageFooterString4 {
            get {
                return ResourceManager.GetString("ReceiptPageFooterString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using {SiteName}!.
        /// </summary>
        internal static string ReceiptPageHeaderString1 {
            get {
                return ResourceManager.GetString("ReceiptPageHeaderString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order and payment has been successfully received..
        /// </summary>
        internal static string ReceiptPageHeaderString2 {
            get {
                return ResourceManager.GetString("ReceiptPageHeaderString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are working as fast as possible on completing your transaction and will send you an e-mail confirmation once completed..
        /// </summary>
        internal static string ReceiptPageHeaderString3 {
            get {
                return ResourceManager.GetString("ReceiptPageHeaderString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order details are as follows: (An e-mail has also been sent).
        /// </summary>
        internal static string ReceiptPageHeaderString4 {
            get {
                return ResourceManager.GetString("ReceiptPageHeaderString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. No..
        /// </summary>
        internal static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESEND CODE.
        /// </summary>
        internal static string ResendCode {
            get {
                return ResourceManager.GetString("ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {SiteName}: Buy Bitcoins.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Type.
        /// </summary>
        internal static string TransferType {
            get {
                return ResourceManager.GetString("TransferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your File.
        /// </summary>
        internal static string UploadYourFile {
            get {
                return ResourceManager.GetString("UploadYourFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USING.
        /// </summary>
        internal static string Using {
            get {
                return ResourceManager.GetString("Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is incorrect..
        /// </summary>
        internal static string VerificationCodeIncorrect {
            get {
                return ResourceManager.GetString("VerificationCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code sent..
        /// </summary>
        internal static string VerificationCodeSent {
            get {
                return ResourceManager.GetString("VerificationCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFICATION OF YOUR IDENTITY.
        /// </summary>
        internal static string VerificationOfIdentity {
            get {
                return ResourceManager.GetString("VerificationOfIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been selected for ID-control..
        /// </summary>
        internal static string VerificationOfIdentityMessageString1 {
            get {
                return ResourceManager.GetString("VerificationOfIdentityMessageString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do this to prevent our platform from being used for fraudulent or illicit activities, a requirement set forth by our banking partners and certain legal jurisdictions..
        /// </summary>
        internal static string VerificationOfIdentityMessageString2 {
            get {
                return ResourceManager.GetString("VerificationOfIdentityMessageString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We kindly ask you to upload a high-resolution copy of your:.
        /// </summary>
        internal static string VerificationOfIdentityMessageString3 {
            get {
                return ResourceManager.GetString("VerificationOfIdentityMessageString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERFICATION OF YOUR MOBILE NUMBER.
        /// </summary>
        internal static string VerificationOfMobileNumber {
            get {
                return ResourceManager.GetString("VerificationOfMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFY ME.
        /// </summary>
        internal static string VerifyMe {
            get {
                return ResourceManager.GetString("VerifyMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a bitcoin address?.
        /// </summary>
        internal static string WhatIsABitcoinAddress {
            get {
                return ResourceManager.GetString("WhatIsABitcoinAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why my mobile number?.
        /// </summary>
        internal static string WhyMyMobileNumber {
            get {
                return ResourceManager.GetString("WhyMyMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES, THAT IS CORRECT.
        /// </summary>
        internal static string YesThatIsCorrect {
            get {
                return ResourceManager.GetString("YesThatIsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You pay.
        /// </summary>
        internal static string YouPay {
            get {
                return ResourceManager.GetString("YouPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bitcoin-address.
        /// </summary>
        internal static string YourBitcoinAddress {
            get {
                return ResourceManager.GetString("YourBitcoinAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive.
        /// </summary>
        internal static string YouReceive {
            get {
                return ResourceManager.GetString("YouReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been selected for ID-control..
        /// </summary>
        internal static string YourOrderHasBeenSelectedForIDControl {
            get {
                return ResourceManager.GetString("YourOrderHasBeenSelectedForIDControl", resourceCulture);
            }
        }
    }
}
