CREATE TABLE [dbo].[User] (
    [Id]                    BIGINT            IDENTITY (100, 1) NOT NULL,
    [RoleId]                BIGINT            NOT NULL,
    [UserType]              BIGINT            NOT NULL,
    [Login]                 NVARCHAR (30)  NULL,
    [Password]              NVARCHAR (256)  NULL,
    [PasswordSalt]          NVARCHAR (256)  NULL,
    [Fname]                 NVARCHAR (50)  NOT NULL,
    [Lname]                 NVARCHAR (30)  NULL,
    [Phone]                 NVARCHAR (20)  NULL,
    [PhoneVerificationCode] BIGINT         NULL,
    [Email]                 NVARCHAR (50)  NULL,
    [Address]               NVARCHAR (30)  NULL,
    [Address2]              NVARCHAR (30)  NULL,
    [Zip]                   NVARCHAR (10)  NULL,
    [City]                  NVARCHAR (30)  NULL,
    [Region]                NVARCHAR (30)  NULL,
    [CountryId]             BIGINT            NULL,
    [LanguageId]            BIGINT            NULL,
    [Commission]            DECIMAL (18, 8)     NULL,
    [KycNote]               NVARCHAR (MAX) NULL,
    [Created]               DATETIME       NOT NULL,
    [Newsletter]            BIT            NULL,
    [PaymentMethodDetails]  NVARCHAR (MAX) NULL,
    [Predecessor]           BIGINT            NULL,
    [Trusted]               DATETIME       NULL,
    [TrustedBy]             BIGINT            NULL,
    [Blocked]               BIT            NULL,
    [BlockedBy]             NVARCHAR (50)  NULL,
    [Tier]					INT			NOT NULL CONSTRAINT [DF_User_Tire] DEFAULT 0, 
	[TierTwoApproved]       DATETIME  NULL,
    [TierTwoApprovedBy]   BIGINT          NULL,
	[TierThreeApproved]     DATETIME  NULL,
    [TierThreeApprovedBy]   BIGINT          NULL,
	[TransactionLimitsDetails]  NVARCHAR (MAX) NULL,
    [UserRiskLevel]			INT			NOT NULL CONSTRAINT [DF_RiskLevel] DEFAULT 0, 
    [SellPaymentMethodDetails] NVARCHAR(MAX) NULL, 
    [CreditCardLimitsDetails] NVARCHAR(MAX) NULL, 
    [DateOfBirth] NVARCHAR(50) NULL, 
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_User_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_User_Language] FOREIGN KEY ([LanguageId]) REFERENCES [dbo].[Language] ([Id]),
    CONSTRAINT [FK_User_User_Trusted] FOREIGN KEY ([TrustedBy]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_User_User_Predecessor] FOREIGN KEY ([Predecessor]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_User_UserType] FOREIGN KEY ([UserType]) REFERENCES [dbo].[UserType] ([Id]),
    CONSTRAINT [FK_User_UserRole] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[UserRole] ([Id])
);



